= BoletIME RDs
:page-layout: repasses_rds
:page-categories: 
:showtitle:

## Congregação

[.colapsador]
--
Reunião 29/09/2022 - Eduardo Janotti
--

[.repasse]
--
No começo deste ano, o IME iniciou a tratar da retirada de verba proveniente de um fundo deixado de "herança" ao instituto e que está previsto investimento exclusivo ao pós-doutorado da unidade. Contudo, até o momento não conseguiram viabilizar o investimento da verba por questões burocráticas.

O prazo para envio de pedidos de cargos de professores titular irá até dezembro deste ano.

Reforçaram o convite ao projeto da Reitoria do Campus, que consiste em um debate com os representantes das congregações das unidades para debater acerca de questões candentes do campus. O evento ocorrerá no dia 17/10 e as pautas da discussão serão elencadas através das sugestões feitas pelos representantes da congregação. Como foi permitido apenas 1 inscrição de representante discente da graduação, mesmo sendo 3 cadeiras de RDs da graduação na congregação, nós conversamos e acordamos de sugerir como pauta na discussão a privatização da universidade pública por meio da falta de política de permanência, falta de contratação de professores, falta de contratação de funcionários e precarização do ensino; na reunião do dia 17/10, a representante da graduação do IME será a Raquissa.

Concurso para professor titular do MAE está sob júdice pois não havia comprovação do título de doutor do candidato (esqueceu de anexar, pois o mesmo tinha pós-doc).

A reitoria não autorizou a realização de reuniões 100% virtuais dos conselhos e comissões, então pelo menos 50% precisa estar presencialmente a partir do dia 24/10.

Propostas de vagas acadêmicas serão disponibilizadas no site e nos ambientes do IME, mas propostas particulares (emprego) serão disponibilizadas em parceria com o aluminai. 

Comentaram do sucesso da feira de profissões, mas que tinha excesso de pessoas. Também foi comentado a falta de água no CRUSP e a aparente contradição entre a feira de profissões ter água, mas o CRUSP não.

O conselho de pesquisa anunciou vários editais abertos, mas que precisa ficar atento aos avisos. Anunciaram o SIICUSP, ocorrendo no IME do dia 17 ao 19/10. Falaram que os alunos de iniciação científica precisam se cadastrar no Atena para poder contabilizar as iniciações científicas, visto que poucos fazem e, sem isso, não podem usar as horas de IC para os créditos de atividades complementares. Contudo, se cadastrar no atena, passa a ser obrigado a presença no SIICUSP. Em compensação, se a IC é com bolsa, ou seja, se precisou assinar termo de outorga, não é mais necessário o cadastro no Atena para contabilizar as horas de AAC, bastando apenas apresentar esse termo.

Sobre a PRPG: vai ocorrer um encontro de pós nos dias 21 e 22/11 e dia 23 será o "Print Day" (?) e várias bolsas capes serão disponibilizadas. A pró-reitoria também está em cima dos cursos online, que agora necessitam serem devidamente justificadas a existência, acarretando ou na regulamentação da disciplina em modo EaD ou voltando a ministrar de modo presencial. O calendário de pós do próximo semestre terá início em 20/03/2023.

Sobre a Pró-Reitoria de Inclusão e Pertencimento (PRIP): vão regimentar as placas inclusivas dos banheiros e vão considerar as auto declarações de gênero para o uso deles. Ainda, teremos 3 vagas de pós-doc abertas para pessoas negras. Comentaram da construção de uma comissão interna do IME relacionado com essa pró-reitoria e que houve chamada de treinamento em saúde mental.

Sobre o resto da pauta, a reunião do dia 27/10 foi transferida pro dia 03/11, foi autorizada a criação da comissão para alteração do regimento interno, mas não foram definidos os membros, será escolhido um membro de cada conselho pelos próprios conselhos, terão até o dia 1/12. Sobre os recursos de aluno, apenas o Gustavo foi retirado de pauta para esclarecer a situação dele, visto que a matrícula foi negada por falta de pré-requisito, mas o aluno comentou que tinha feito matérias (que não estão no histórico) que dispensariam ele.
Sobre o título de professor emérito, também foi retirado de pauta pois não havia 2/3 da congregação para votar.
--

[.colapsador]
--
Reunião 17/11/2022 - Raquissa
--

[.repasse]
--
Foi falado sobre a volta da obrigação das máscaras em locais fechados, a obrigatoriedade da dose de reforço (apenas a primeira, a segunda não é necessária) e sobre evitar aglomerações.

A respeito da copa, ficou decidido que os profs conversem com os alunos se eles terão aula ou não.

Foi mencionada uma possível boas-vindas aos professores que retornaram da Ucrânica.

Os cursos de verão foram autorizados.

SISU pela própria USP foi autorizado.

Disciplinas de pós-graduação poderão ser presenciais OU não presenciais, não podem existir disciplinas híbridas. Se tiver alguma coisa a distância, a disciplina será considerada não presencial.

Foram feitos os pedidos de reposição dos claros docentes dos professores exonerados ou falecidos a partir de 2019.

Votação para a aprovação da emeritação de um professor foi adiada devido a falta de quórum. A congregação pede novamente que, na próxima reunião, todos os membros compareçam.
--

## Comissão de Graduação (CG)

[.colapsador]
--
Reunião 20/09/2022 - Eduardo Janotti
--

[.repasse]
--
Anunciaram algumas mudanças que devem ser realizadas no vestibular.

Devem adicionar conteúdo de sociologia, filosofia, artes e educação física na fuvest, mas não foi anunciado o que será retirado.

A USP deve abandonar o sisu e fazer uma seleção própria a fim de ganhar um tempo entre as notas do enem e o sisu, possibilitando que o semestre seja iniciado antes sem que haja muitos alunos chegando ao longo do semestre devido as outras chamadas.

Sobre a vacinação, estão pedindo que o camat ajude a divulgar a informação sobre colocar a terceira dose no sistema. A usp vai começar a cancelar esses alunos do sistema. Contudo, a usp não deu prazo para quando esses alunos serão cancelados, então a data presente nos cartazes (20/10) foi uma estabelecida pela própria CG, torcendo para que a data da usp seja depois disso 
Em outras palavras, os alunos precisam cadastrar a terceira dose urgentemente.

Vão oferecer uma optativa livre no primeiro semestre de nivelamento de matemática, focada em resolver vários exercícios. Eles vão até pedir ajuda ao camat e a outros professores sobre o que colocar nessa disciplina e como lidar com ela.

A pró-reitoria de inclusão e pertencimento está criando o programa ecos (Escuta, Cuidado e Orientação em Saúde Mental) e o IME será um exemplo nesse programa. Pretendem criar uma unidade específica apenas para o IME, focada em atendimento psicológico
--