= BoletIME RDs
:page-layout: repasses_rds
:page-categories:
:showtitle:

## Comissão de Inclusão e Pertencimento (CIP)
[.colapsador]
--
Reunião 14/08/2023 - Guelfi
--

[.repasse]
--
Repasse da reunião da CIP de 14/08/2023 
Haviam dois pontos de pauta, a formação de bancas de heteroidentificação para concursos e a adaptação para alunes autistas

Bancas de heteroidentificação: 
Recentemente o CO aprovou um projeto de ações afirmativas para vagas de docentes e servidores, e como parte desse processo surgiu a necessidade de criação de bancas de heteroidentificação para avaliar candidatos que queiram concorrer a vagas destinadas a PPI. Nos concursos relativos ao IME, cabe a CIP indicar essas bancas. A banca deve ser formada sempre por um número impar de pessoas, ou seja, pelo menos 3, e além disso cada uma deve ter um suplente, e é preciso também uma banca para julgar os recursos com uma configuração igual, ou seja, ao menos 12 pessoas são necessárias para compor essa banca. É possível que essas bancas precisarão ser compostas parcialmente por docentes que não se identifiquem como PPI, pois poucas unidades contam com um número suficiente de docentes pertencentes a esses grupos. Algumas soluções possíveis podem ser formar a banca com servidores ou então formar a banca com pessoas de diferentes unidades (como uma grande banca para todos os concursos do baixo matão), mas essas possibilidades ainda estão sendo avaliadas. A PRIP organizará as bancas dos concursos de servidores não-docentes, mas os concursos de docentes são muito numerosos então é difícil que a PRIP centralize essas bancas também

Adaptações para estudantes autistas
Foi novamente mencionado que muitas unidades começaram a agir em relação a adaptações porque se trata de lei para PCDs. Foi mencionado que em reunião com estudantes autistas do IME, a maior queixa é em relação a condições de avaliação, em especial tempo extra para avaliações e salas isoladas para diminuir o barulho. Foi mencionado que na pós-graduação, os estudantes autistas procuram muito a secretária da pós, o que tem sobrecarregado ela. Foi proposto que se criasse um forms onde e estudante poderia enviar, antes do inicio do semestre, seus laudos médicos, e solicitar as adaptações necessárias. Isso poderia ser usado para a atribuição de salas, de forma que as salas mais silenciosas ficassem reservadas para turmas com estudantes que precisam de adaptação. Foi levantado o problema de que não há funcionário que possa ajudar com esse processo na reserva de salas, bem como a questão da lei de proteção de dados. Foi proposto um mapeamento des estudantes de pós que são autistas, tendo em vista fazer um mapeamento da graduação também no futuro.
--

## GT AcolhIME

O GT foi transformado na CIP. Este repasse é anterior a isso.

[.colapsador]
--
Reunião 01/12/2022 - Raquissa
--

[.repasse]
--
Encaminhado proposta de escrita do protocolo de recepção de novos docentes. Atualmente, docentes contratados não tem acompanhamento durante o início de suas atividades, de modo a dificultar a integração e a compreensão dos processos do instituto e da universidade. A ideia surge visando melhorar a inserção do novo docente em sua função e na comunidade do IME e da USP.

Como a próxima congregação (08/12) deverá votar a criação da Comissão de Inclusão e Pertencimento (CIP) - órgão subordinado ao Conselho de Inclusão e Pertencimento (CoIP) da Pró-Reitoria de Inclusão e Pertencimento -, a sugestão do GT AcolhIME é a de garantir a nomeação de, no mínimo, 5 docentes a fim de garantir a representação discente e de técnicos-administrativos. Tal mínimo é necessário, dado que pelas regras da USP, só é possível representação de estudantes e funcionários configurando de 10% de docentes (sempre arredondando pra cima). Ainda, o GT AcolhIME se posicionou em vista de considerar a CIP mais burocrática e menos representativa do que o GT, de modo a optar pela não extinção do GT mesmo com a criação da nova comissão. A proposta será de reformular o GT permitindo maior participação de discentes e funcionários, buscando um conselho paritário.

A questão de saúde mental foi discutida. Há extrema dificuldade em conseguir apoio psicológico (atendimento) devido a restrição de verba do instituto. Alternativamente, está se buscando parcerias com o IAG e o IF, que já possuem esse atendimento e outros projetos ligados à saúde mental. Pontuado também a possibilidade de se buscar informações em outros locais, na comunidade ao redor da USP (São Remo, Butantã e etc), principalmente no relacionado a SPDM - Associação Paulista para o Desenvolvimento de Medicina (https://rastsbutanta.spdmafiliadas.org.br/)    
--