= Carta aberta à comunidade graduanda do IME-USP
:showtitle:

Na próxima semana, entre os dias 13 e 14 de dezembro, ocorrerá a eleição para decidir quais estudantes ocuparão as vagas do próximo mandato da representação discente nas comissões e colegiados do IME-USP.

Acreditamos na necessidade de fortalecer a política de representação discente, prezando pela comunicação e transparência entre es representantes discentes, bem como o esforço em manter ativos e atualizados os repasses para a comunidade acadêmica. O nosso trabalho deve ter como central a elevação da atuação da representação discente no IME, conquistando cada vez mais avanços quanto às demandas candentes no instituto. Por isso, nos posicionamos contrários às chapas concorrentes pelo Movimento Correnteza, que recentemente marcou uma plenária vazia para tratar de representação discente sem sequer contatar os atuais representantes discentes (afinal, estes não contam com nenhuma representação no IME e não conhecem a dinâmica do nosso Instituto) e se recusando a falar com membros de outra representação discente do IME, o CAMat. O movimento ainda assim lançou suas candidaturas, o que evidencia seu caráter oportunista de autoconstrução, não tendo nada de positivo a oferecer aos estudantes do Instituto.

Reforçamos que o objetivo da representação discente é esta: representar a discência do Instituto, es estudantes. Essa representação só pode ser feita se houver contato com os representados - pois somente assim se sintetiza as demandas-, e se houver disposição para lutar por essas demandas. Da nossa parte, há, pois não buscamos autoconstruções, mas tornar o IME um instituto que bem atenda sua comunidade.

Dessa forma, fazemos um chamado à comunidade graduanda para que participem das
plenárias de apresentação e conheçam e se apropriem de nossas candidaturas para cada comissão e colegiado.

NOTURNO > 09/12, às 18h, via google meet 

DIURNO > 12/12, às 13h, saguão do bloco B.

08 de Dezembro de 2022.