= BoletIME RDs
:page-layout: repasses_rds
:page-categories:
:showtitle:

## GT AcolhIME

[.colapsador]
--
Reunião 01/12/2022 - Raquissa
--

[.repasse]
--
Encaminhado proposta de escrita do protocolo de recepção de novos docentes. Atualmente, docentes contratados não tem acompanhamento durante o início de suas atividades, de modo a dificultar a integração e a compreensão dos processos do instituto e da universidade. A ideia surge visando melhorar a inserção do novo docente em sua função e na comunidade do IME e da USP.

Como a próxima congregação (08/12) deverá votar a criação da Comissão de Inclusão e Pertencimento (CIP) - órgão subordinado ao Conselho de Inclusão e Pertencimento (CoIP) da Pró-Reitoria de Inclusão e Pertencimento -, a sugestão do GT AcolhIME é a de garantir a nomeação de, no mínimo, 5 docentes a fim de garantir a representação discente e de técnicos-administrativos. Tal mínimo é necessário, dado que pelas regras da USP, só é possível representação de estudantes e funcionários configurando de 10% de docentes (sempre arredondando pra cima). Ainda, o GT AcolhIME se posicionou em vista de considerar a CIP mais burocrática e menos representativa do que o GT, de modo a optar pela não extinção do GT mesmo com a criação da nova comissão. A proposta será de reformular o GT permitindo maior participação de discentes e funcionários, buscando um conselho paritário.

A questão de saúde mental foi discutida. Há extrema dificuldade em conseguir apoio psicológico (atendimento) devido a restrição de verba do instituto. Alternativamente, está se buscando parcerias com o IAG e o IF, que já possuem esse atendimento e outros projetos ligados à saúde mental. Pontuado também a possibilidade de se buscar informações em outros locais, na comunidade ao redor da USP (São Remo, Butantã e etc), principalmente no relacionado a SPDM - Associação Paulista para o Desenvolvimento de Medicina (https://rastsbutanta.spdmafiliadas.org.br/)    
--