= Uma confissão presumivelmente desnecessária
// :page-subtitle:
:page-identificador: 20240401_uma_confissao_presumivelmente_desnecessaria
:page-data: "23 de abril de 2024"
:page-layout: boletime_post
:page-categories: [boletime_post]
:page-tags: ['BoletIME']
:page-boletime: "Abril/2024 (10ed)"
:page-autoria: 'Carlos Marques'
// :page-autoria-completa: ''
:page-resumo: ['Relato sobre como é estar no ambiente universitário sendo autista.']

[.aviso-vermelho]
--
O texto a seguir foi enviado via forms de contato do BoletIME e não necessariamente condiz com a opinião do corpo editorial.
--

Não sei se, a essa altura do campeonato, a confissão do óbvio se faz necessária: uso um determinado cordão característico e participo de um coletivo cujo símbolo, uma raposinha bem fofinha, tem um elemento que também está presente em meu cordão. Mas, a soma do bombardeio de informações sobre um determinado tema bastante comentado neste mês de abril com um desejo antigo meu resultou na inspiração para a escrita dessas palavras e para fazer a dita confissão presumivelmente desnecessária: eu sou uma pessoa autista. É bem verdade que, alguns anos atrás, essas palavras saiam de mim produzindo a mesma sensação que se tem quando se toma um shot com um só gole, mas tal sensação, com o tempo, está se tornando cada vez mais suave. E, se eu consigo falar sobre autismo de forma cada vez mais confortável, é porque a experiência universitária me deu essa possibilidade. Mas, até trajetória... chegar a esse ponto de minha vida, percorri uma longa.

Ao contrário de uma louvável tendência atual, meu diagnóstico veio cedo, no longínquo 2005, aos meus 8 anos de idade, numa época em que pouco se falava sobre autismo. Depois de tanto tempo, era a resposta que minha família procurava para explicar minhas esquisitices: ficava vidrado vendo a máquina de lavar centrifugar roupa, rodava tudo o que via pela frente, surtava quando não escreviam o meu nome com a cor azul, vivia fazendo aquilo que hoje chamamos de stims ou estereotipias. . . E, mesmo com tudo isso, eu era tido como uma criança extremamente inteligente (uma fake news na qual muita gente cai até hoje). Talvez por conta disso, não precisei de uma intervenção clínica mais intensa. Evidente que sofri bullying e abusos na escola: pela falta de traquejo social, não percebia que se aproveitavam bastante de mim, mas, aos trancos e barrancos, sobrevivi à escola, conservando a fama de aluno brilhante (desde aquela época, as fake news se propagam com velocidade rápida). Não sei se tinha mais algum outro aluno autista nas escolas em que passei. O que sei é que, por muito tempo, nunca tive contato com outras pessoas autistas, e é possível que isso tenha tido uma interferência significativa na minha não-aceitação.

Como muita gente sabe, tentei, desde 2015, entrar no BCC, e apenas consegui em 2021 (hoje vejo isso como um hiperfoco do qual não me arrependo de ter tido). Os meus primeiros dias (e, por extensão, o meu primeiro ano) como imeano foram felizes e vergonhosos: a vida pandêmica possibilitava o conforto de não precisar abrir a câmera e não mandar áudio e, consequentemente, não mostrar o ser esquisitinho que sou. Devem ter pensado que eu era um chatbot e, na verdade, tenho dificuldade de mandar áudio e gravar vídeo de mim mesmo até hoje (inclusive, ainda não consigo ver a gravação da minha dança com minha irmã na festa de debutante dela). Por mais que minha Semana de Recepção tenha sido divina e, por meio dela, eu tenha sido submetido a uma overdose intensa de carinho, ainda tinha fiapos de receio de como me acolheriam e veriam quando todos nós voltássemos para o presencial.

E voltamos, lá em 2022. Certa vez me contaram que, na primeira reunião presencial da Comissão de Recepção depois de tanto tempo, já perceberam que eu era “diferente”. Desde aquela ocasião, daquele primeiro contato presencial com a comunidade imeana, confesso que nunca passei por uma experiência de bullying ou escrotidão comparável, um motivo de tranquilidade tanto para mim quanto para minha família. Muito pelo contrário: me sinto muito bem acolhido pelas pessoas do IME, e percebo que há uma certa preocupação comigo (bastante evidente nestas últimas semanas, alías). Mesmo assim, ainda faltava realizar um desejo que tinha cada vez mais forte em mim e que sentia que iria me ajudar bastante.

Via com alegria o fato de existir o Coletivo Autista da USP (CAUSP), mas tinha bastante receio de entrar: seria uma atitude que explicitaria ainda mais o óbvio que todo mundo já tinha percebido. Após meses e meses de densas reflexões, resolvi entrar, e, com certeza, foi uma das decisões mais acertadas da minha graduação. O contato com outras pessoas autistas é bastante frutuoso, e, com elas, me sinto em casa, me sinto um irmão, um semelhante. Apenas uma pessoa autista consegue entender, com bastante profundidade, as alegrias e tristezas de uma outra pessoa autista. O CAUSP é um ambiente no qual posso falar com segurança sobre minhas dificuldades e demônios internos, que atormentam a vida de qualquer pessoa autista. Nele, me descubro e redescubro enquanto autista, uma das melhores dádivas que a vida universitária me concedeu. Nele também, tenho contato com reflexões sobre as dificuldades específicas dos autistas na vida universitária, e é surreal pensar que faço parte do longo processo de se tentar mitigar essas dificuldades (as quais, aos poucos, estou descobrindo que também tenho): ajudei a gestar o tal do “Guia sobre autismo para professores e funcionários da USP”, que tem servido de base para a reflexão pedagógica de alguns institutos da universidade. E não esperava aparecer no Jornal da USP justamente em reportagens sobre autismo. São experiências que aquele vestibulando persistente não imaginava que iria viver.

Não posso dizer que estou plenamente satisfeito com o estado atual das coisas: há diversas questões a serem trabalhadas ainda no meu processo de autoaceitação e há presumidas ortodoxias pedagógicas, ainda vistas de modo dogmático no IME-USP, que precisam ser superadas (ou, ao menos, questionadas com mais intensidade), porque sua ineficiência atinge inclusive os neurotípicos. Ainda assim, há centelhas de esperança quando professores chegam em mim preocupados em fazer provas adaptadas ou quando amigos demonstram preocupação com o fato de eu não conseguir suportar ambientes sensorialmente exigentes. Essas centelhas de esperança (que deixam o coração quentinho), somadas à beleza das vivências que tenho enquanto membro do CAUSP, me fazem um uspiano não apenas feliz, mas cada vez mais disposto a seguir o conselho escrito na minha camiseta do coletivo do qual tenho tanto orgulho de participar: “ame sua mente tanto quanto seu corpo”.