= IME Wolves se classifica para os playoffs da Ignis Cup
// :page-subtitle:
:page-identificador: 20240423_ime_wolves_se_classifica_ignis_cup
:page-data: "23 de abril de 2024"
:page-layout: boletime_post
:page-categories: [boletime_post]
:page-tags: ['BoletIME']
:page-boletime: "Abril/2024 (10ed)"
:page-autoria: 'Guelfi'
// :page-autoria-completa: ''
:page-resumo: ['Após dois jogos da Goddess Tour, a equipe de LoL inclusivo do IME Wolves garantiu sua vaga nos playoffs da Ignis Cup, o maior campeonato de LoL Inclusivo do Brasil. "É a primeira vez que um time de LoL universitário se classifica para essa etapa da competição", é o que conta Susana, diretora da modalidade no IME. Ela explica a relevância do naipe inclusivo, que é disputado por atletas mulheres e de gêneros não-binários, que tem poucos incentivos no cenário de E-Sports tradicional.']

Após dois jogos da Goddess Tour, a equipe de LoL inclusivo do IME Wolves garantiu sua vaga nos playoffs da Ignis Cup, o maior campeonato de LoL Inclusivo do Brasil. "É a primeira vez que um time de LoL universitário se classifica para essa etapa da competição", é o que conta Susana, diretora da modalidade no IME. Ela explica a relevância do naipe inclusivo, que é disputado por atletas mulheres e de gêneros não-binários, que tem poucos incentivos no cenário de E-Sports tradicional.

"O cenário inclusivo vem crescendo a cada ano e um de seus objetivos é dar visibilidade às mulheres e não-binários no competitivo de LoL, criando um espaço mais acolhedor para esse público. Isso motivou que surgisse, também, o cenário inclusivo universitário, onde competimos".

A próxima etapa do campeonato acontece em 07/05, o IME Wolves enfrentará a paiN Gaming e os jogos serão transmitidos pelo canal do CBLOL na Twitch. O time de LoL Inclusivo está no https://www.instagram.com/imelamb/[Instagram] e no https://www.twitter.com/@imelamb[Twitter] como *@imelamb*.