= A solitude nas Matemáticas
// :page-subtitle:
:page-identificador: 20240423_a_solitude_nas_matematicas
:page-data: "23 de abril de 2024"
:page-layout: boletime_post
:page-categories: [boletime_post]
:page-tags: ['BoletIME']
:page-boletime: "Abril/2024 (10ed)"
:page-autoria: 'Leitores'
// :page-autoria-completa: ''
:page-resumo: ['Uma reflexão sobre com as Matemáticas - e exatas como um todo - podem alienar seus estudantes de experiências e vontades, trazendo um questionamento ao final.']

Quando perguntam-nos "o que você faz?" e respondemos falando "Matemática" junto com os seus objetos de estudo, a conversa sempre estagna na conclusão de "tem que ser muito inteligente para entender essas coisas" e não vai para frente. Por vezes, a pessoa pode vir a dizer que odiou Matemática na escola, tornando aquele assunto, novamente, difícil de progredir. Assim, para alguém não familiarizado com a linguagem Matemática, parece não existir uma linha de diálogo por se tratar, de fato, de um campo de estudo de saberes muito especializado. Até mesmo entre as próprias matemáticas e matemáticos, em muitos casos, não existe uma clareza no entender sobre o trabalho do outro por causa dessa hiper-especialização. Descobrimos tanta coisa da Matemática em tantas áreas distintas que se tornou impossível uma pessoa, dentro do razoável, dominar de fato nem sequer uma fração dela. Agora, assim como outras profissões, é claro que matemáticas e matemáticos não trabalham só para que outros os reconheçam. Tudo que se faz é pelo interesse e paixão que se tem pela Matemática, em busca de algo que cada um julga ser o horizonte imaginativo de um mundo melhor. Mas a falta dessa abertura genuína para o diálogo torna a Matemática solitária por se tratar de um objeto de estudo que confina o universo de saberes dentro da cabeça de cada uma e cada um que trabalha e manipula este objeto.

Pela própria natureza do ato corajoso de estudar, é quase como regra que, em algum momento, a pessoa não entenda um teorema, um conceito, ou qualquer coisa que seja. Faz parte da busca pelo conhecimento. Dentro das Matemáticas, no entanto, como consequência da solitude que é a manipulação dos objetos matemáticos serem confinados nas cabeças daqueles que ousaram almejá-los e tentar tocá-los, os seus sofrimentos, também, se confinam dentro das pessoas. Não é raro a percepção auto-depreciativa de "sou burro mesmo para Matemática" ao longo do curso numa lógica de "se todos ao meu redor parecem entender essas coisas dentro da cabeça delas, a única explicação para eu não entender é que sou menos, sou burro". Um talvez poderia argumentar para a pessoa ir atrás de ajuda. Nisso, alguns de fato vão. Mas são muitos outros que, somando todo estigma que se tem pela Matemática tanto daqueles impostos pela realidade maior na qual estamos todos inseridos - como fato da Matemática ser considerada a matéria mais odiada nas escolas - tanto daqueles que surgem dentro dos próprios cursos das Matemáticas, torna a ideia de socializar o aprendizado muito alienante.

Essa alienação, por sua vez, é de certa forma retroalimentada pela própria maneira como se trabalha a Matemática, tanto atualmente quanto historicamente. Quando vamos atrás da história da Matemática, percebemos que a grande maioria dos matemáticos "ocidentais" e também "orientais" eram, de fato, socialmente e financeiramente abastados; era algo da elite, para poucos. Essa percepção não é coincidência. A Matemática exige tempo. A única forma efetiva de aprender sequer uma fração dela é fazendo Matemática. É muito difícil entender e estudá-la quando não se aloca quantidades absurdas de horas, dias e semanas para fazer o exercício da Matemática. Por um, todo tempo que se aloca para a Matemática é o tempo que se desloca do social, da família, do lazer. É algo doloroso de se perceber. Assim, o exercício da Matemática acaba se tornando uma experiência que pode afastar a matemática e o matemático das pessoas ao seu redor; por outro lado, muitos talvez nem sequer tenham a possibilidade de olhar para essa realidade do tempo que a Matemática demanda. Os acasos da vida exigem, por vezes, que não dediquemos tempo para fazer uma lista ou ler um livro. Não é à toa que historicamente a Matemática parece ser algo da aristocracia. Nisso, a percepção perigosa e errônea de que todos ao seu redor parecem conseguir conciliar a vida e estar fazendo essa lista e lendo o livro, cria um ciclo vicioso de se colocar no lugar de incapaz.

São situações que, de maneiras muito análogas, existem nas outras exatas. As engenharias, assim como a Matemática, também sofrem dessa alienação; o estudo da Física, da Química, também. Porém, algo que diferencia a Matemática de uma maneira muito única é justamente o fato dos objetos que se estudam nela estarem confinados nas nossas cabeças, quase impossibilitados de serem compartilhados. Diferente da Física, das engenharias, da Químia, que abrem diálogos diretas com o cotidiano, a Matemática parece ser, nesse sentido, só uma ferramenta que outras exatas utilizam - e que, muitas vezes, é igualmente odiada pelos próprios estudantes dessas outras exatas, numa imagem às suas experiências escolares -. Para um estudante de Física, essa pessoa pode usar do seu conhecimento para expor o princípio dos objetos do cotidiano; um estudante das engenharias pode, por sua vez, relacionar as infraestruturas do dia-a-dia com seu curso; Químicas também. As Matemáticas, porém, se tratam de objetos puramente teóricos: não são um reflexo direto do mundo material. Estes objetos se parecem muito mais como expressões da pura lógica do que de uma "realidade" propriamente dita. E essa natureza abstrata das Matemáticas acaba por afastar, também, aqueles não familiarizados com ela.

Nesse sentido, existe também um movimento inverso das Matemáticas se afastarem das outras áreas - incluindo das outras exatas -. Talvez seja um mecanismo de defesa, mas não é incomum encontrar opiniões que colocam a Matemática como algo superior a todas as outras exatas, quase num movimento esnobista. Isso, também, se reflete até dentro das diversas Matemáticas. Assim, fica o questionamento, talvez, de se esse isolamento, esse esnobismo são algo puramente opinativa dos próprios estudantes, ou se é reflexo de algo maior que define a maneira como o IME e todas as outras faculdades de exatas enxergam os seus próprios cursos, e da ideia maior de "exatas".
