= Do uso do banheiro
// :page-subtitle:
:page-identificador: 20240423_do_uso_do_banheiro
:page-data: "23 de abril de 2024"
:page-layout: boletime_post
:page-categories: [boletime_post]
:page-tags: ['BoletIME']
:page-boletime: "Abril/2024 (10ed)"
:page-autoria: "Leitores"
// :page-autoria-completa: ''
:page-resumo: ['Tutorial de como utilizar banheiros em forma de uma paródia satírica.']

[.aviso-vermelho]
--
O texto a seguir foi enviado via forms de contato do BoletIME e não necessariamente condiz com a opinião do corpo editorial.
--

Um "banheiro" pode ser definido como local dotado de equipamentos sanitários que permite realizar as necessidades fisiológicas e a higiene pessoal. Em muitos lugares ainda, o banheiro é dividido em masculino e feminino. Masculino e feminino é uma divisão dicotômica e incompleta, mas socialmente aceita para seres humanos. Os seres humanos são animais mamíferos, bípedes, que se distinguem de outros mamíferos como gatos e bípedes como galinhas principalmente por duas características: o telencéfalo altamente desenvolvido e o polegar opositor. De maneira geral, eles costumam viver em sociedade. Uma sociedade é um agrupado de seres que convivem em um determinado período de tempo e espaço, em um estado de colaboração mútua, com um senso de coletividade.

O telencéfalo altamente desenvolvido, por sua vez, permite aos seres humanos uma capacidade extraordinária de captar, armazenar, processar e relacionar informações. Enquanto isso, o polegar opositor permite o movimento de pinça dos dedos, que permite a execução de tarefas de precisão. O telencéfalo altamente desenvolvido combinado com o movimento de pinça dos dedos permitiu aos seres humanos a construção de uma miríade de infraestruturas para as suas sociedades. Uma dessas infraestruturas é o banheiro, local dotado de equpamentos sanitários que permite realizar as necessidades fisiológicas e a higiene pessoal, com primeiros registros dessa infraestrutura em 3000 A.C.

Diferentemente dos gatos domésticos que utilizam caixas de areia para as suas necessidades, os seres humanos usam um tipo de equipamento sanitário chamado de vaso sanitário. Um vaso sanitário - coloquialmente chamado de privada - é um objeto utilizado para satisfazer as necessidades fisiológicas do ser humano, que possui telencéfalo altamente desenvolvido e polegar opositor. O seu funcionamento é bastante simples: o vaso retém uma quantia de água, que ao efetuar o ato da descarga - ou seja, liberação de uma quantidade controlada de água -, leva os dejetos através de um sifão, terminando no esgoto. Um sifão é um dispositivo hídrico em formato de S com intuito de prender uma quantidade específica de água a fim de evitar que o cheiro desagradável do esgoto volte para o banheiro; um esgoto é o local onde os dejetos de banheiros são levados para centrais de tratamento.

No esgoto proliferam todo tipo de bactérias e patógenos que por sua vez causam doenças. As doenças afetam o bem-estar e o bom funcionamento dos seres humanos. Mesmo quando não causam doenças, podem cheirar mal. O cheiro é uma sensação que animais como seres humanos, gatos e galinhas possuem em resposta aos estímulos químicos do meio captados pelos quimiorreceptores dos seus narizes. Certos componentes causam sensação de bem-estar, como perfumes, enquanto que outros causam mal-estar, como o cheiro de esgoto.

Portanto, para que uma sociedade de seres humanos possa funcionar, é necessário que sejam diminuídas as sensações de mal-estar que cada um dos seres humanos causa nos demais seres humanos. Portanto, um ambiente não pode estar com mal-cheiro como de esgotos. Para isso, todo ser humano com telencéfalo altamente desenvolvido e polegar opositor deve fazer o uso correto do vaso sanitário - ou privada - dando a descarga após o uso; que não deve ser difícil para um ser humano, já que a capacidade extraordinária de captar, armazenar, processar e relacionar informações do seu telencéfalo altamente desenvolvido entende que o sifão - dispositivo hídrica em formato de S com intuito de evitar que o cheiro desagradável do esgoto volte para o banheiro - não funciona se a fonte do cheiro estiver antes do sifão, e o seu polegar opositor mais do que é o suficiente para apertar o botão da descarga. Para tal, foi preparado um manual de instruções para o bom uso e da preservação do espaço de banheiros, que deve ser facilmente compreendido dado telencéfalo altamente desenvolvido do leitor:

- Levante a tampa do vaso sanitário. Caso convém, levante o assento também;
- Retirar/baixar qualquer peça de roupa que possa porventura impedir a satisfação das necessidades fisiológicas do momento;
- Realize as suas necessidades fisiológicas dentro do vaso sanitário;
- Ao terminar, limpe a si mesmo com papel higiênico disponível em cada um dos cubículos;
- Recoloque/levante qualquer peça de roupa que tenha retirado ou baixado;
- Feche a tampa do vaso sanitário;
- Aperte o botão localizado geralmente acima da caixa d’água do vaso sanitário OU na parede que encosta o vaso sanitário (a depender do modelo);
- Saia do cubículo, e lave as mãos.

