= BoletIME RDs
:page-layout: repasses_rds
:page-categories: 
:showtitle:

## Departamentos

### MAT

[.colapsador]
--
Reunião 21/09/2022 - Thiago Guelfi
--

[.repasse]
--
A pauta principal da reunião foram licenças de professores em relação ao ano que vem, e o impacto disso na carga didática, com desdobramento no défict de professores. 

Muitos professores pedem licença para desempenhar atividades de pesquisa em Universidades fora do Brasil, ou mesmo para se dedicar a atividades pessoais, e a prática comum é que o professor lecione um pouco mais de disciplinas nos semestres anteriores a licença para aliviar a carga dos demais docentes que vão permanecer no Brasil e ter que cobrir as aulas deste durante a estadia fora. 

Contudo, devido ao défict no quadro de professores, a média de créditos de disciplinas oferecidas pelos docentes já vem sendo maior que aquela prevista teoricamente, o que faz com que a maioria dos professores estejam acumulando "créditos" que justificariam sua licença posterior.

O problema é que, no cenário atual, caso as licenças (que vale reforçar, são um direito trabalhista dos professores, e tem inúmeros benefícios para a atividade de pesquisa) sejam aprovadas, a quantidade de créditos restante para os docentes no Brasil se tornará impraticável, justamente devido ao déficit de professores no Departamento de Matemática.

Isso pode agravar problemas que já estamos enfrentando, como a escassez de oferecimento de optativas, tanto na graduação quanto na pós, e uma qualidade inferior no ensino, devido a sobrecarga dos docentes. Esses problemas estão ligados diretamente aos estudantes e sobre os quais devemos nos atentar.
--

### MAE

Ainda sem repasses.

### MAC

Ainda sem repasses.

### MAP

Ainda sem repasses.