= BoletIME RDs
:page-layout: repasses_rds
:page-categories: 
:showtitle:

## Conselho Técnico-Administrativo (CTA)

[.colapsador]
--
Reunião 09/02/2023 - Ivan Kuvasney Lima
--

[.repasse]
--
1 - As reformas vistas no bloco B são pra saídas de emergência. Na porta de vidro, do lado da B4 (que vai deixar de ser sala de aula por ter tido o tamanho reduzido) e outras no andar superior. Todas realizadas pela SEF pro prédio estar no conforme dos bombeiros. O reservatório de água (apelidado de "pirulitão" pelo Sérgio) também está lá para estar no conforme dos bombeiros, para controle de incêndio (e uso geral também). Sua posição foi definida pela SEF e a diretoria pretende realizar ainda algumas reformas ao redor dele para ser um ambiente mais habitável, incluindo até pintura do pirulitão.

2 - Na próxima reunião, o Sérgio quer que sejam trazidas demandas para poder realizar um planejamento financeiro do IME. Alguns chefes de departamento mencionaram hoje sobre troca de cadeiras e persianas, mas ainda vão trazer algo mais certo depois de conversar com os departamentos. 

3- a ATAAC tava com uma ideia de contratar dois estagiários para atender aos estudantes do noturno (seria um atendimento presencial das 18h às 22h) e tirar dúvidas gerais que eles possam ter. A contratação foi aprovada, mas precisa abrir edital e ter algumas reuniões pra definir exatamente o trabalho, mas provavelmente incluiria comunicação digital e até um FAQ pra responder aos estudantes sobre abertura e etapas de requerimento, subir coisas de AAC, etc.
--


[.colapsador]
--
Reunião 02/03/2023 - Ivan Kuvasney Lima
--

[.repasse]
--
- Reitoria aprovou o mérito da construção de um Bloco Didático para o IME, como contrapartida para a ampliação do BCC, e a SEF (Superintendência de Espaços Físicos) mandou o primeiro projeto. Este inclui 4 andares, um café, salas de aula, salas de estudo, e espaços ao ar livre para estudos e confraternização. O projeto está agora nas mãos de uma comissão de professores do IME dedicada à construção deste novo bloco, que passará a contar com a participação do RD do CTA (e possivelmente mais).

- ATAAC ficou responsável por organizar uma reunião entre chefes do departamento e coordenadores dos cursos para eles entenderem melhor como funciona o Apoio ao BCC e pensar na implementação de estruturas parecidas em outros cursos. Sugeri de serem convidados também os RDs das CoCs.
--